STANDARD_USER = ""
STANDARD_PASSWORD = ""
LOCKED_OUT_USER = "invalid_user"
URL = "https://automationexercise.com"
INVENTORY_URL = ""
LOW_TO_HIGH = "Price (low to high)"
HIGH_TO_LOW = "Price (high to low)"
PRODUCT_LANDING_PAGE_TITLE = "Products"
ERROR_LOGIN_FAILED = "Epic sadface: Username and password do not match any user in this service"
DEFAULT_WAIT = 10
SHORT_WAIT = 5
LONG_WAIT = 20
PRODUCT_TITLES = ["''", "''"]
FIRST_NAME = ""
LAST_NAME = ""
POSTAL_CODE = ""
ORDER_SUCCESS_MESSAGE = "T"
PRODUCT_NAMES = ['Sauce Labs Backpack', 'Sauce Labs Bike Light']
ORDER_CONFIRMATION_PAGE_TITLE = "Checkout: Complete!"